config/routes.rb
Organizer::Application.routes.draw do
  resources :tasks

  resources :task_lists

end

app/models/task.rb
class Task
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning
  include Mongoid::Paranoia

  belongs_to :task_list

  belongs_to :parent_task,
      :inverse_of => :subtasks,
      :class_name => 'Task'
  has_many :subtasks,
      :inverse_of => :parent_task,
      :class_name => 'Task'

  field :name,         :type => String
  field :due_at,       :type => Time
  field :description,  :type => String
  field :importance,   :type => Integer, :default => 0
  field :urgency,      :type => Integer, :default => 0
  field :color,        :type => Integer
  field :completed_at, :type => Time
end

app/models/task_list.rb
class TaskList
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia

  has_many :tasks

  belongs_to :parent_list,
      :inverse_of => :sublists,
      :class_name => 'TaskList'
  has_many :sublists,
      :inverse_of => :parent_list,
      :class_name => 'TaskList'

  field :name,             :type => String
  field :due_at,           :type => Time
  field :description,      :type => String
  field :default_priority, :type => Integer
  field :color,            :type => Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  # GET /task_lists
  # GET /task_lists.json
  def index
    @task_lists = TaskList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @task_lists }
    end
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
    @task_list = TaskList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task_list }
    end
  end

  # GET /task_lists/new
  # GET /task_lists/new.json
  def new
    @task_list = TaskList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task_list }
    end
  end

  # GET /task_lists/1/edit
  def edit
    @task_list = TaskList.find(params[:id])
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(params[:task_list])

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: 'Task list was successfully created.' }
        format.json { render json: @task_list, status: :created, location: @task_list }
      else
        format.html { render action: "new" }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /task_lists/1
  # PUT /task_lists/1.json
  def update
    @task_list = TaskList.find(params[:id])

    respond_to do |format|
      if @task_list.update_attributes(params[:task_list])
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list = TaskList.find(params[:id])
    @task_list.destroy

    respond_to do |format|
      format.html { redirect_to task_lists_url }
      format.json { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Use this to set the page title in the view. Nifty!
  def title(page_title)
    content_for(:title) { page_title }
  end

  def link_to_named_after(object, options = {})
    name = object.name if object.respond_to? :name
    name ||= object.title if object.respond_to? :title
    name ||= object.to_s if object.respond_to? :to_s
    name ||= object.to_param if object.respond_to? :to_param
    name ||= object.inspect
    link_to(name, url_for(object), options)
  end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/layouts/application.html.haml
!!! html
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= [yield(:title), "Organizr"].compact.join(" - ")
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

    /[if lt IE 9]
      = stylesheet_link_tag 'ie'
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

  %body
    %header#header
      %hgroup
        %h1.site_title
          = link_to "Organizr", '/'
        %h2.section_title= yield :title
        /
          .btn_view_site
            = link_to "View Site", 'http://www.medialoot.com'

    %section#secondary_bar
      .user
        /
          %p
            John Doe (
            %a{:href => "#"}> 3 Messages
            )
          %a{:class => :logout_user, :href => "#", :title => "Logout"} Logout

      .breadcrumbs_container
        %article.breadcrumbs
          = link_to "Website Admin", 'index.html'
          .breadcrumb_divider &gt;
          = link_to "Dashboard", 'index.html'
          .breadcrumb_divider &gt;
          = link_to "Dashboard", 'index.html'
          .breadcrumb_divider &gt;
          %a.current Dashboard

    %aside#sidebar.column
      %form.quick_search
        %input{:type => "text", :placeholder => "Quick Search", :name => "search" }
      %hr/

      #nav
        %h3 Calendar
        %ul.toggle
          %li.events_new= link_to "New Event", 'events/new'
          %li.events= link_to "View Calendar", 'events/'
          %li.events_agenda= link_to "Agenda", 'events/agenda'
          %li.event_settings= link_to "Settings", 'events/settings'

        %h3 Tasks
        %ul.toggle
          %li.tasks_new= link_to "New Task", 'tasks/new'
          %li.tasks= link_to "View Tasks", 'tasks/'
          %li.task_lists= link_to "View Task Lists", 'task_lists/'

        %h3 Admin
        %ul.toggle
          %li.options= link_to "Options", 'options'
          %li.security= link_to "Security", 'security'
          %li.signout= link_to "Logout", 'signout'

      %footer
        %p
          %strong Copyright © 2011 RTLong Geek Services
        %p
          Theme by
          = link_to "MediaLoot", 'http://www.medialoot.com'

    %section#main.column
      - flash.each do |name,msg|
        = content_tag :div, msg , :id => "flash_#{name}", :class => "alert_#{name}"
      -#
        %h4.alert_info Welcome to the free MediaLoot admin panel template, this could be an informative message.
        %h4.alert_warning A Warning Alert
        %h4.alert_error An Error Message
        %h4.alert_success A Success Message

      %article.module.width_full
        /
          %header
            %h3 Header
        .module_content
          = yield
      /
        %article.module.width_full
          %header
            %h3 Stats
          .module_content
            %article.stats_graph
              %img{:alt => "", :height => "140", :src => "http://chart.apis.google.com/chart?chxr=0,0,3000&chxt=y&chs=520x140&cht=lc&chco=76A4FB,80C65A&chd=s:Tdjpsvyvttmiihgmnrst,OTbdcfhhggcTUTTUadfk&chls=2|2&chma=40,20,20,30", :width => "520"}/
            %article.stats_overview
              .overview_today
                %p.overview_day Today
                %p.overview_count 1,876
                %p.overview_type Hits
                %p.overview_count 2,103
                %p.overview_type Views
              .overview_previous
                %p.overview_day Yesterday
                %p.overview_count 1,646
                %p.overview_type Hits
                %p.overview_count 2,054
                %p.overview_type Views
            .clear
      /
        %article.module.width_3_quarter
          %header
            %h3.tabs_involved Content Manager
            %ul.tabs
              %li
                = link_to "Posts", '#tab1'
              %li
                = link_to "Comments", '#tab2'
          .tab_container
            #tab1.tab_content
              %table.tablesorter{:cellspacing => "0"}
                %thead
                  %tr
                    %th
                    %th Entry Name
                    %th Category
                    %th Created On
                    %th Actions
                %tbody
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Lorem Ipsum Dolor Sit Amet
                    %td Articles
                    %td 5th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Ipsum Lorem Dolor Sit Amet
                    %td Freebies
                    %td 6th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Sit Amet Dolor Ipsum
                    %td Tutorials
                    %td 10th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Dolor Lorem Amet
                    %td Articles
                    %td 16th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Dolor Lorem Amet
                    %td Articles
                    %td 16th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/

            #tab2.tab_content
              %table.tablesorter{:cellspacing => "0"}
                %thead
                  %tr
                    %th
                    %th Comment
                    %th Posted by
                    %th Posted On
                    %th Actions
                %tbody
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Lorem Ipsum Dolor Sit Amet
                    %td Mark Corrigan
                    %td 5th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Ipsum Lorem Dolor Sit Amet
                    %td Jeremy Usbourne
                    %td 6th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Sit Amet Dolor Ipsum
                    %td Super Hans
                    %td 10th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Dolor Lorem Amet
                    %td Alan Johnson
                    %td 16th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/
                  %tr
                    %td
                      %input{:type => "checkbox"}/
                    %td Dolor Lorem Amet
                    %td Dobby
                    %td 16th April 2011
                    %td
                      %input{:src => "/assets.png", :title => "Edit", :type => "image"}
                      %input{:src => "/assets.png", :title => "Trash", :type => "image"}/
      /
        %article.module.width_quarter
          %header
            %h3 Messages
          .message_list
            .module_content
              .message
                %p Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.
                %p
                  %strong John Doe
              .message
                %p Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.
                %p
                  %strong John Doe
              .message
                %p Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.
                %p
                  %strong John Doe
              .message
                %p Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.
                %p
                  %strong John Doe
              .message
                %p Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.
                %p
                  %strong John Doe
          %footer
            %form.post_message
              %input{:onfocus => "if(!this._haschanged){this.value=''};this._haschanged=true;", :type => "text", :value => "Message"}
              %input.btn_post_message{:type => "submit", :value => ""}/

      / .clear
      /
        %article.module.width_full
          %header
            %h3 Post New Article
          .module_content
            %fieldset
              %label Post Title
              %input{:type => "text"}
            %fieldset
              %label Content
              %textarea{:rows => "12"}
            %fieldset{:style => "width:48%; float:left; margin-right: 3%;"}
              -# to make two field float next to one another, adjust values accordingly
              %label Category
              %select{:style => "width:92%;"}
                %option Articles
                %option Tutorials
                %option Freebies
            %fieldset{:style => "width:48%; float:left;"}
              -# to make two field float next to one another, adjust values accordingly
              %label Tags
              %input{:style => "width:92%;", :type => "text"}
            .clear
          %footer
            .submit_link
              %select
                %option Draft
                %option Published
              %input.alt_btn{:type => "submit", :value => "Publish"}
                %input{:type => "submit", :value => "Reset"}

      /
        %article.module.width_full
          %header
            %h3 Basic Styles
          .module_content
            %h1 Header 1
            %h2 Header 2
            %h3 Header 3
            %h4 Header 4
            %p Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras mattis consectetur purus sit amet fermentum. Maecenas faucibus mollis interdum. Maecenas faucibus mollis interdum. Cras justo odio, dapibus ac facilisis in, egestas eget quam.
            %p
              Donec id elit non mi porta
              = link_to "link text", '#url'
              gravida at eget metus. Donec ullamcorper nulla non metus auctor fringilla. Cras mattis consectetur purus sit amet fermentum. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.
            %ul
              %li Donec ullamcorper nulla non metus auctor fringilla.
              %li Cras mattis consectetur purus sit amet fermentum.
              %li Donec ullamcorper nulla non metus auctor fringilla.
              %li Cras mattis consectetur purus sit amet fermentum.
      .spacer

app/views/task_lists/_form.html.haml
= form_for @task_list do |f|
  -if @task_list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task_list.errors.count, "error")} prohibited this task_list from being saved:"
      %ul
        - @task_list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :due_at
    = f.datetime_select :due_at
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :default_priority
    = f.number_field :default_priority
  .field
    = f.label :color
    = f.number_field :color
  .actions
    = f.submit 'Save'

app/views/task_lists/edit.html.haml
- title "Editing Task List: #{@task_list.name}"

= render 'form'

= link_to 'Show', @task_list
\|
= link_to 'Back', task_lists_path

app/views/task_lists/index.html.haml
- title "Lists"

%table
  %tr
    %th Name
    %th Due at
    %th Description

  - @task_lists.each do |task_list|
    %tr
      %td= link_to task_list.name, task_list
      %td= task_list.due_at
      %td= task_list.description


= link_to 'New Task List', new_task_list_path

app/views/task_lists/new.html.haml
- title "New Task List"

= render 'form'

= link_to 'Back', task_lists_path

app/views/task_lists/show.html.haml
- title @task_list.name

%p
  %b Name:
  = @task_list.name
%p
  %b Due at:
  = @task_list.due_at
%p
  %b Description:
  = @task_list.description
%p
  %b Default priority:
  = @task_list.default_priority
%p
  %b Color:
  = @task_list.color

= link_to 'Edit', edit_task_list_path(@task_list)
\|
= link_to 'Back', task_lists_path

app/views/tasks/_form.html.haml
= form_for @task do |f|
  -if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :due_at
    = f.datetime_select :due_at
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :importance
    = f.number_field :importance
  .field
    = f.label :urgency
    = f.number_field :urgency
  .actions
    = f.submit 'Save'

app/views/tasks/edit.html.haml
- title "Editing task"

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
- title "Tasks"

%table
  %tr
    %th.color_bar
    %th Name
    %th Due at

  - @tasks.each do |task|
    %tr
      %td.color_bar
      %td= link_to_named_after task
      %td= task.due_at

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
- title "New task"

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
- title 'Task'

%p
  %b Name:
  = @task.name
%p
  %b Due at:
  = @task.due_at
%p
  %b Description:
  = @task.description
%p
  %b Importance:
  = @task.importance
%p
  %b Urgency:
  = @task.urgency
%p
  %b Color:
  = @task.color
%p
  %b Completed at:
  = @task.completed_at

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path